### ISSUE TITLE
4.	legyen egy oldal, ahol a választott adatbázisból jelenít meg adatokat. Ehhez 3 tábla adatait használja fel az adatbázisból.

### ISSUE THREAD

**Issue by balmrk** [balmrk/Cukraszda#5]

**Comment by Engi16** [comment]
Most nézem, ez a süti oldalunk, ugye?
Meg akkor ez a többtáblás rész lesz a tanultakból?
Ha jól gondolom, akkor a miénk egyelőre egy táblából vesz adatokat, de szólj, ha tévedek
